INSERT INTO ALUMNOS ( ID_ALUMNO, APELLIDO1, APELLIDO2, NOMBRE, EDAD) VALUES ( 255, 'Antúnez', 'Pérez', 'Luis', 20);
INSERT INTO ALUMNOS ( ID_ALUMNO, APELLIDO1, APELLIDO2, NOMBRE, EDAD) VALUES ( 256, 'Rodríguez', 'Gámez', 'María', 23);
INSERT INTO ALUMNOS ( ID_ALUMNO, APELLIDO1, APELLIDO2, NOMBRE, EDAD) VALUES ( 257, 'Bernáldez', 'Gutiérrez', 'Ana Isabel', 21);
INSERT INTO ALUMNOS ( ID_ALUMNO, APELLIDO1, APELLIDO2, NOMBRE, EDAD) VALUES ( 258, 'Pérez', 'Rodríguez', 'José', 24);
INSERT INTO ALUMNOS ( ID_ALUMNO, APELLIDO1, APELLIDO2, NOMBRE, EDAD) VALUES ( 259, 'Rodríguez', 'Gámez', 'María', 19);
COMMIT;
/